services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=file:./dev.db
      - JWT_SECRET=honeychain_production_jwt_secret_key_sih2026_truetag_64chars
      - NEXT_PUBLIC_RPC_URL=https://rpc-amoy.polygon.technology
      - NEXT_PUBLIC_CONTRACT_ADDRESS=0x5FbDB2315678afecb367f032d93F642f64180aa3
      - NEXT_PUBLIC_AI_SERVICE_URL=http://ai_service:8000
      - AI_SERVICE_URL=http://ai_service:8000
    depends_on:
      - ai_service

  ai_service:
    build:
      context: ./ai_service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
