[platformio]
default_envs = wiscore_rak4631
src_dir = firmware/src
include_dir = firmware/include

[env:wiscore_rak4631]
platform = nordicnrf52
board = wiscore_rak4631
framework = arduino
monitor_speed = 115200
build_flags =
    -I firmware/config
    -I firmware/include
    -D NRF52840_XXAA
    -D BEEVIL_FIRMWARE_VERSION=\"2.1.0-bench\"
lib_deps =
    Wire
    SPI
