function h = drawBus(ax, points, bus_name, style, options)
% DRAWBUS Draws a thicker engineering signal or power bus through multi-segment points
% points = [x1, y1; x2, y2; x3, y3; ...]

if nargin < 5; options = struct(); end
if ~isfield(options, 'color'); options.color = style.stroke_dark; end
if ~isfield(options, 'line_width'); options.line_width = style.lw_bus; end
if ~isfield(options, 'line_style'); options.line_style = '-'; end

h.line = plot(ax, points(:,1), points(:,2), ...
    'Color', options.color, ...
    'LineWidth', options.line_width, ...
    'LineStyle', options.line_style);

if ~isempty(bus_name)
    mid_idx = ceil(size(points, 1) / 2);
    tx = points(mid_idx, 1);
    ty = points(mid_idx, 2) + 0.02;
    h.label = text(ax, tx, ty, bus_name, ...
        'FontName', style.font_family, ...
        'FontSize', style.fs_tag, ...
        'FontWeight', 'bold', ...
        'Color', options.color, ...
        'HorizontalAlignment', 'center', ...
        'VerticalAlignment', 'bottom');
end

end
