function h = drawDecisionNode(ax, center_pt, size_dim, condition_str, style)
% DRAWDECISIONNODE Draws a rhomboid decision diamond for firmware or model flow
% center_pt = [cx, cy], size_dim = [w, h]

cx = center_pt(1); cy = center_pt(2);
w = size_dim(1); h_dim = size_dim(2);

rx = [cx, cx + w/2, cx, cx - w/2];
ry = [cy + h_dim/2, cy, cy - h_dim/2, cy];

h.diamond = fill(ax, rx, ry, style.fill_card, ...
    'EdgeColor', style.stroke_dark, ...
    'LineWidth', style.lw_regular);

h.text = text(ax, cx, cy, condition_str, ...
    'FontName', style.font_family, ...
    'FontSize', style.fs_tag, ...
    'FontWeight', 'bold', ...
    'Color', style.stroke_dark, ...
    'HorizontalAlignment', 'center', ...
    'VerticalAlignment', 'middle');

end
