function fig = fig10_end_to_end_dataflow()
% FIG10_END_TO_END_DATAFLOW Generates Figure 10: End-to-End Data Flow Pipeline
% IEEE HardwAIre Challenge Phase 2 — BEEVIL KNIEVEL
% Chronological 6-Stage Signal Transformation: Physical Phenomena to Beekeeper Decision [Video Frame Ready]

addpath(fullfile(fileparts(mfilename('fullpath')), '..', 'lib'));
style = createFigureStyle('standard');

fig = figure('Name', 'FIG 10: End-to-End Data Flow Pipeline', ...
    'Color', style.bg_color, ...
    'Position', [100, 100, style.width, style.height], ...
    'MenuBar', 'none', 'ToolBar', 'none');
ax = axes('Parent', fig, 'Position', [0, 0, 1, 1]);
hold(ax, 'on'); axis(ax, [0 1 0 1]); axis(ax, 'off');

% Header
text(ax, 0.035, 0.965, 'FIGURE 10: END-TO-END DATA FLOW PIPELINE', ...
    'FontName', style.font_family, 'FontSize', style.fs_title, 'FontWeight', 'bold', ...
    'Color', style.stroke_dark, 'VerticalAlignment', 'top');
text(ax, 0.035, 0.935, 'Chronological 6-Stage Signal Transformation: Physical Phenomena to Beekeeper Decision [Video Frame Ready]', ...
    'FontName', style.font_family, 'FontSize', style.fs_body, 'Color', style.stroke_med, 'VerticalAlignment', 'top');

stages = {
    'STAGE 1: PHYSICAL', ...
    {'Brood Core Thermal:', '34.5°C to 35.5°C', ...
     'Acoustic Vibrations:', '100–500 Hz Audio', ...
     'CO2 Respiration:', '400–5000 ppm', ...
     'Colony Mass Accum:', '0–100 kg Net Weight'}, 'VALIDATED';
    
    'STAGE 2: TRANSDUCTION', ...
    {'Brood Core RTD:', 'TMP117 NIST ±0.1°C', ...
     'Thermal Gradient:', '5x DS18B20 1-Wire', ...
     'Bio-Acoustic MEMS:', 'INMP441 16kHz I2S', ...
     'Env & Scale Sensors:', 'SCD41 & HX711 Load'}, 'VALIDATED';
    
    'STAGE 3: EMBEDDED DSP', ...
    {'CMSIS-DSP Real FFT:', '256-pt in 2.49 ms', ...
     '8 Energy Bins:', 'Worker Piping Surge', ...
     'Page''s CUSUM Filter:', '-0.02°C/hr Queenless', ...
     'Binary Struct Pack:', '33-Byte LoRa Packet'}, 'MEASURED';
    
    'STAGE 4: DUAL RADIO', ...
    {'BLE Mesh Cluster:', 'nRF52840 (2.4 GHz)', ...
     'Semtech SX1262 TX:', '+14 dBm Config ERP', ...
     'IN865 LoRa Backhaul:', '865.0625 MHz SF7', ...
     'Star Link Range:', '4.2 km Line-of-Sight'}, 'CALCULATED';
    
    'STAGE 5: GATEWAY AI', ...
    {'Raspberry Pi 3B+:', 'Waveshare LoRa HAT', ...
     'SQLite WAL Engine:', 'beevil_telemetry.db', ...
     'Edge AI (Model 2):', 'Random Forest (94%)', ...
     'Validation Protocol:', 'CRC-16 & Node Check'}, 'VALIDATED';
    
    'STAGE 6: BEEKEEPER UI', ...
    {'Local Web PWA:', 'beevil.local Daemon', ...
     'Predictive Alerts:', 'Swarm & Queenless', ...
     'Target Intervention:', 'Single-Frame Entry', ...
     'Zero Cloud Fees:', '100% Offline Edge'}, 'DEMONSTRATED'
};

col_w = 0.142;
col_h = 0.70;
y_pos = 0.16;

for i = 1:6
    cx = 0.030 + (i-1) * 0.158;
    title_str = stages{i, 1};
    lines = stages{i, 2};
    tag = stages{i, 3};
    drawBlock(ax, [cx, y_pos, col_w, col_h], title_str, lines, style);
    drawEvidenceTag(ax, [cx + col_w - 0.082, y_pos + col_h - 0.025, 0.08, 0.022], tag, style);
    if i < 6
        drawArrow(ax, [cx + col_w, y_pos + col_h/2], [cx + 0.158, y_pos + col_h/2], '', style);
    end
end

labels = {'PHYSICAL', 'EDGE', 'EDGE / DSP', 'WIRELESS', 'GATEWAY / AI', 'DECISION'};
for i = 1:6
    cx = 0.030 + (i-1) * 0.158 + col_w/2;
    text(ax, cx, 0.100, labels{i}, 'FontName', style.font_family, 'FontSize', style.fs_subhead, ...
        'FontWeight', 'bold', 'Color', style.stroke_dark, 'HorizontalAlignment', 'center');
end

drawLegend(ax, [0.18, 0.016, 0.64, 0.036], style);

end
