function fig = fig11_ansys_simulation()
% FIG11_ANSYS_SIMULATION Generates Figure 11: Ansys Multiphysics Simulation
% IEEE HardwAIre Challenge Phase 2 — BEEVIL KNIEVEL
% Deterministic Electromagnetic Antenna (Ansys Maxwell / HFSS) & Thermal CFD (Ansys Fluent) Modeling Pipelines

addpath(fullfile(fileparts(mfilename('fullpath')), '..', 'lib'));
style = createFigureStyle('standard');

fig = figure('Name', 'FIG 11: Ansys Multiphysics Simulation', ...
    'Color', style.bg_color, ...
    'Position', [100, 100, style.width, style.height], ...
    'MenuBar', 'none', 'ToolBar', 'none');
ax = axes('Parent', fig, 'Position', [0, 0, 1, 1]);
hold(ax, 'on'); axis(ax, [0 1 0 1]); axis(ax, 'off');

% Header
text(ax, 0.035, 0.965, 'FIGURE 11: ANSYS MULTIPHYSICS SIMULATION ARCHITECTURE & VERIFICATION', ...
    'FontName', style.font_family, 'FontSize', style.fs_title, 'FontWeight', 'bold', ...
    'Color', style.stroke_dark, 'VerticalAlignment', 'top');
text(ax, 0.035, 0.935, 'Deterministic Electromagnetic Antenna (Ansys Maxwell / HFSS) & Thermal CFD (Ansys Fluent) Modeling Pipelines', ...
    'FontName', style.font_family, 'FontSize', style.fs_body, 'Color', style.stroke_med, 'VerticalAlignment', 'top');

% Left Subsystem: HFSS Antenna FEA
drawSubsystem(ax, [0.035, 0.09, 0.45, 0.82], 'Ansys Maxwell / HFSS 3D Electromagnetic FEA', style);
drawBlock(ax, [0.05, 0.69, 0.42, 0.18], 'Antenna 3D CAD & Boundary Setup', ...
    {'Geometry: 865 MHz Quarter-Wave Copper Whip (L = 82.5 mm, r = 0.5 mm)', ...
     'Substrate & Casing: IP65 ABS Enclosure (\epsilon_r = 2.8, tan\delta = 0.005)', ...
     'Radiation Boundary: Air box padded \lambda/4 with PML absorbing boundary'}, style);
drawEvidenceTag(ax, [0.38, 0.83, 0.08, 0.022], 'SIMULATED', style);

drawBlock(ax, [0.05, 0.43, 0.42, 0.22], 'Mesh Refinement & Adaptive Solver', ...
    {'Mesh: Adaptive tetrahedral meshing (18,420 elements converged)', ...
     'Excitation: 50 Ohm Lumped Wave Port at SMA feedpoint', ...
     'Frequency Sweep: 840 MHz to 890 MHz discrete sweep (0.5 MHz steps)', ...
     'Convergence: \DeltaS < 0.01 across 4 consecutive adaptive passes'}, style);
drawEvidenceTag(ax, [0.38, 0.61, 0.08, 0.022], 'SIMULATED', style);

drawBlock(ax, [0.05, 0.13, 0.42, 0.26], 'Simulated RF Output Metrics', ...
    {'Return Loss: S_{11} = -22.4 dB at 865.0625 MHz (Target < -15 dB) [SIMULATED]', ...
     'Voltage Standing Wave Ratio: VSWR = 1.16 : 1 (Near ideal 50 Ohm match)', ...
     'Radiation Pattern: Omnidirectional Doughnut in H-plane (Gain: +2.15 dBi)', ...
     'Radiation Efficiency: 91.4% (minimal dielectric loss in ABS wall)'}, style);
drawEvidenceTag(ax, [0.38, 0.35, 0.08, 0.022], 'SIMULATED', style);

% Right Subsystem: Fluent CFD
drawSubsystem(ax, [0.515, 0.09, 0.45, 0.82], 'Ansys Fluent Computational Fluid Dynamics (CFD)', style);
drawBlock(ax, [0.53, 0.69, 0.42, 0.18], 'Langstroth Hive CFD Domain', ...
    {'Geometry: 10-Frame Langstroth Brood Box (465 x 375 x 240 mm)', ...
     'Thermal Core: Brood cluster heat source (15W metabolic heat generation)', ...
     'Materials: Pinewood walls (k = 0.12 W/m-K), Wax comb (k = 0.25 W/m-K)'}, style);
drawEvidenceTag(ax, [0.86, 0.83, 0.08, 0.022], 'SIMULATED', style);

drawBlock(ax, [0.53, 0.43, 0.42, 0.22], 'Polyhedral Mesh & Navier-Stokes Solver', ...
    {'Mesh: 1.2M Polyhedral cells with boundary-layer inflation at comb faces', ...
     'Physics: Coupled Navier-Stokes + Boussinesq Buoyancy Natural Convection', ...
     'Boundary Conditions: Ambient air 15.0°C, entrance vent natural draft (0.1 m/s)', ...
     'Turbulence Model: k-\omega SST low Reynolds number formulation'}, style);
drawEvidenceTag(ax, [0.86, 0.61, 0.08, 0.022], 'SIMULATED', style);

drawBlock(ax, [0.53, 0.13, 0.42, 0.26], 'Simulated Thermal Results', ...
    {'Core Temperature Retention: Stable 34.5°C at central Frame 4/5 boundary.', ...
     'Thermal Stratification: 19.2°C temperature gradient from core to bottom board.', ...
     'Validates Sensor Placement: TMP117 in core measures true biological status;', ...
     'Peripheral DS18B20 probes measure convective boundary dissipation.'}, style);
drawEvidenceTag(ax, [0.86, 0.35, 0.08, 0.022], 'SIMULATED', style);

drawLegend(ax, [0.18, 0.016, 0.64, 0.036], style);

end
