import { Farmer, FieldOfficer, HiveStatus } from './types';

export const DEFAULT_FARMER: Farmer = {
  farmerId: 'KVIC-BK-9402',
  phoneNumber: '9876543210',
  name: 'Ramesh Patel',
  preferredLanguage: 'hi',
  voiceEnabled: true,
  clusterId: 'KVIC-GUJ-ANAND-04',
  fieldOfficerId: 'FO-KVIC-782',
  walletAddress: '0x71C7656EC7ab88b098defB751B7401B5f6d8976F',
  hiveIds: [101, 102, 103, 104, 105, 106, 107, 108],
};

export const MOCK_FIELD_OFFICER: FieldOfficer = {
  fieldOfficerId: 'FO-KVIC-782',
  name: 'Sanjay Sharma',
  phoneNumber: '+91 94250 12345',
  clusterId: 'KVIC-GUJ-ANAND-04',
  roleTitle: 'Senior Apiary Nodal Officer (KVIC)',
  avatarUrl: '/officer_avatar.png',
};

export const INITIAL_HIVES: HiveStatus[] = [
  {
    hiveId: 101,
    farmerId: 'KVIC-BK-9402',
    hiveName: 'North Apiary #1',
    xPos: 20,
    yPos: 25,
    lastSeenAt: new Date().toISOString(),
    temperatureC: 34.2,
    humidityPct: 58,
    vocIndex: 42,
    acousticActivityLevel: 'normal',
    overallStatus: 'healthy',
    activeRisks: [],
  },
  {
    hiveId: 102,
    farmerId: 'KVIC-BK-9402',
    hiveName: 'North Apiary #2',
    xPos: 50,
    yPos: 20,
    lastSeenAt: new Date().toISOString(),
    temperatureC: 38.6,
    humidityPct: 72,
    vocIndex: 88,
    acousticActivityLevel: 'high',
    overallStatus: 'alert',
    activeRisks: [
      {
        id: 'risk-102-1',
        hiveId: 102,
        type: 'swarm',
        severity: 'high',
        confidence: 0.96,
        recommendedAction: 'action_add_super',
        detectedAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
      },
    ],
  },
  {
    hiveId: 103,
    farmerId: 'KVIC-BK-9402',
    hiveName: 'Center Yard #3',
    xPos: 80,
    yPos: 30,
    lastSeenAt: new Date().toISOString(),
    temperatureC: 36.1,
    humidityPct: 62,
    vocIndex: 65,
    acousticActivityLevel: 'high',
    overallStatus: 'watch',
    activeRisks: [
      {
        id: 'risk-103-1',
        hiveId: 103,
        type: 'pest',
        severity: 'medium',
        confidence: 0.89,
        recommendedAction: 'action_check_mites',
        detectedAt: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
      },
    ],
  },
  {
    hiveId: 104,
    farmerId: 'KVIC-BK-9402',
    hiveName: 'Center Yard #4',
    xPos: 30,
    yPos: 60,
    lastSeenAt: new Date().toISOString(),
    temperatureC: 33.8,
    humidityPct: 55,
    vocIndex: 38,
    acousticActivityLevel: 'normal',
    overallStatus: 'healthy',
    activeRisks: [],
  },
  {
    hiveId: 105,
    farmerId: 'KVIC-BK-9402',
    hiveName: 'East Corner #5',
    xPos: 70,
    yPos: 65,
    lastSeenAt: new Date().toISOString(),
    temperatureC: 41.2,
    humidityPct: 81,
    vocIndex: 112,
    acousticActivityLevel: 'high',
    overallStatus: 'alert',
    activeRisks: [
      {
        id: 'risk-105-1',
        hiveId: 105,
        type: 'temperature',
        severity: 'high',
        confidence: 0.94,
        recommendedAction: 'action_provide_shade',
        detectedAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
      },
    ],
  },
  {
    hiveId: 106,
    farmerId: 'KVIC-BK-9402',
    hiveName: 'West Orchard #6',
    xPos: 15,
    yPos: 85,
    lastSeenAt: new Date(Date.now() - 4 * 3600 * 1000).toISOString(), // 4 hours ago - stale
    temperatureC: 34.0,
    humidityPct: 56,
    vocIndex: 40,
    acousticActivityLevel: 'low',
    overallStatus: 'no_signal',
    activeRisks: [],
  },
];
